apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: replica
      app.kubernetes.io/name: neo4j
  template:
    metadata:
      labels:
        app.kubernetes.io/component: replica
        app.kubernetes.io/name: neo4j
    spec:
      containers:
        - command:
            - /bin/bash
            - '-c'
            - >
              echo "Starting Neo4j READ_REPLICA on $HOST"
              exec /docker-entrypoint.sh "neo4j"
          image: neo4j:4.0.3-enterprise
          name: neo4j
          securityContext:
            readOnlyRootFilesystem: true
